### PR TITLE
IH013-52 - ADR_10273-40 - Interactive elements have no visible focus …

### PR DESCRIPTION
**Pull request by sebastianchristopher**
…indicator

 * add styling on focus

### CODE REVIEW

**Comment by buckett** [comment]
Why not use the `:focus` selector?
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus

**Comment by sebastianchristopher** [comment]
> Why not use the `:focus` selector? https://developer.mozilla.org/en-US/docs/Web/CSS/:focus

The focus is actually on the `<a>`, not the `<div>` (the parent), so I would have to use `:focus-within` which doesn't work with Internet Explorer. Unless there's another way of doing it?

**Comment by buckett** [comment]
IE11 is no longer supported by Canvas so using https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within if fine.

**Comment by buckett** [comment]
I re-ran the actions script and it worked it time .....

**Review by buckett — APPROVED** [review]

**Pull request merged**
