### PR TITLE
Shippable: Perform weekly builds of the tests.

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Comment by buckett** [comment]
Can we split out testing of the current skin on beta against testing of the current code against a Canvas node?

**Comment by buckett** [comment]
I'm keen that the weekly test doesn't use the js/css from the local checkout but checks that the currently deployed skin works as expected.

**Comment by mpellicer** [comment]
Tests are already splitted and I'm working on other suites to test the currently deployed theme against pre-created courses.

This PR just adds the cron resource to check if the build is triggered automatically.

**Comment by buckett** [comment]
Fine to merge, but would be good to have a job that just runs the tests that target beta/test.

**Comment by mpellicer** [comment]
I'm working on both suites right now, one for beta and one for live!

**Pull request merged**
