### PR TITLE
Complete the suite of tests forcing the CPN logic. Added another test suite for an empty course.

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Comment by buckett** [comment]
Could we separate out the test that just check that Canvas has specific elements we're expecting and those that test the code in the current checkout? They are quite different in what they are testing.

How does the ENV var work if that code is already in the beta skin? Do we get into a timing issue where it may end up running the script twice (once for the version in the skin and once for the version added by puppeteer)?

**Comment by mpellicer** [comment]
Sounds good, I'll work on a refactor of the test suites so they perform tests for different purposes.

The ENV variable belongs to Canvas, the script will not run twice because the first time the attribute does not exist in the ENV variable, after inserting the current checkout script, it will perform the script because the attribute exists. Does this make sense?

**Comment by mpellicer** [comment]
Hi @buckett, I've splitted the tests into separate suites, every suite checks its specific purpose.

I'm planning to create more suites for existing courses, creating the courses in production was VERY helpful as I have the same test courses in both environments, with the deployed script.

https://canvas.ox.ac.uk/courses/42437
https://universityofoxford.beta.instructure.com/courses/42437

Also the token should be valid for both environments, it's just perform the tests in a different domain.

Sounds good?

**Comment by buckett** [comment]
On 1 Oct 2020, at 11:38, Miguel Pellicer <notifications@github.com> wrote:
> Hi @buckett, I've splitted the tests into separate suites, every suite checks its specific purpose.

Brilliant, thanks.

> I'm planning to create more suites for existing courses, creating the courses in production was VERY helpful as I have the same test courses in both environments, with the deployed script.
> 
> https://canvas.ox.ac.uk/courses/42437
> https://universityofoxford.beta.instructure.com/courses/42437
> 
> Also the token should be valid for both environments, it's just perform the tests in a different domain.

Yep, the tokens get copied across along with all the accounts. I don’t think we want the user to be able to create course anywhere other than in the testing -> CPN sub-account, but we could grant the user access to existing courses in other parts of the sub-account tree if needed.

— 
  Matthew Buckett, Senior VLE Developer

  Systems and Applications, Technology Enhanced Learning
  Centre for Teaching and Learning, University of Oxford
  13 Banbury Road, OX2 6NN
  Tel: 01865 283349

**Comment by mpellicer** [comment]
Are you ok to merge this? I'll work on the weekly tests against beta and production using pre-created courses.

Thanks again for the good support!

**Comment by buckett** [comment]
Thanks for the good work. 👍

**Pull request merged**
